---
  title: 'Classification'
  output: rmarkdown::github_document
---

In classification, we predict the qualitative response or the category, which means we classify the observations to a category or a class. Most of the classification methods first predict the probability that the observation belongs to each of the categories and then assign the label of the category which has the highest probability. There are two main types of classification methods:

1. Linear Classification 
  * Logistic Regression
  * Support Vector Machine (SVM)

2. Non-linear Classification
  * $K$-nearest neighbor (K-NN)
  * Kernel Support Vector Machine (SVM)
  * Random Forests.
  
# Logistic Regression

In logistic regression insted of modeling the response $Y$ directly, we model the probaility that $Y$ belongs to a particular category. For convenience we are using the generic 0/1 coding for the response. Using a linear regression model we model the probability
$$
\[
    p = Pr(Y=1|X) = \beta_0 + \beta_1 X.
\]
$$
We must model $p$ using a function that gives output between 0 and 1 for all the values of X. In logistic regression, we use the logistic function
$$
\[
      p = \dfrac{e^{\beta_0 + \beta_1 X}}{1+e^{\beta_0 + \beta_1 X}}.
\]
$$
Then
$$
\[
    \dfrac{p}{1-p} = e^{\beta_0 + \beta_1 X}, 
\]
$$
where the quantity $p/(1-p)$ is called the odds, and can take on any value between 0 and $\infty$. By taking the logarithm of both sides
$$
\[
  ln (\dfrac{p}{1-p}) = \beta_0 + \beta_1 X.
\]
$$
The left-hand side is called the log-odds or logit and this logit is linear in $X$.